// src/lib/components/Hero.svelte
<script>
	import logo from '$lib/images/tired-blue-whale.png';
	import { Section } from './sections';
	import Greeting from './Greeting.svelte';

	/**
	 * @type {number}
	 */
	let outerHeight;

	function scrollDown() {
		window.scrollTo({
			top: outerHeight * 1.1,
			left: 0,
			behavior: 'smooth'
		});
	}
</script>

<svelte:window bind:outerHeight />

<Section sectionId="hero" zIndex="z-[10]">
	<section class="h-full flex justify-center items-center bg-hero">
		<div class="relative flex flex-col-reverse md:flex-row justify-center items-center">
			<div>
				<div class="overflow-clip">
					<h1 class="text-6xl md:text-7xl lg:text-9xl px-4 py-2 text-right animate-hero-title">
						Tired<br />Blue Whale
					</h1>
				</div>
				<div class="flex justify-center">
					<div class="h-1 bg-white animate-hero-bar" />
				</div>
				<div class="overflow-clip">
					<h2 class="text-4xl md:text-5xl lg:text-6xl px-4 py-2 text-right animate-hero-sub-title">
						Works
					</h2>
				</div>
			</div>
			<div class="w-8" />
			<div class="overflow-clip">
				<img
					class="h-48 md:h-64 lg:h-96 aspect-square animate-hero-logo"
					alt="Tired Blue Whale Logo"
					src={logo}
				/>
			</div>
			<div class="absolute right-0 -bottom-3 lg:-bottom-16 left-0 translate-y-full">
				<Greeting />
			</div>
		</div>
		<div class="absolute bottom-0 left-0 right-0 flex justify-center animate-intro">
			<div class="flex-1 max-w-header flex justify-end pr-4 xl:pr-8 pb-4 xl:pb-8">
				<button
					type="button"
					class="rounded-full border-2 p-2 animate-bounce"
					aria-label="Scroll down"
					on:click={scrollDown}
				>
					<svg
						class="w-4 h-4 xl:w-8 xl:h-8 text-gray-800 dark:text-white"
						aria-hidden="true"
						xmlns="http://www.w3.org/2000/svg"
						fill="none"
						viewBox="0 0 10 14"
					>
						<path
							stroke="currentColor"
							stroke-linecap="round"
							stroke-linejoin="round"
							stroke-width="2"
							d="M5 1v12m0 0 4-4m-4 4L1 9"
						/>
					</svg>
				</button>
			</div>
		</div>
	</section>
</Section>

// components/Hero.tsx
import { Wave } from "./Wave";

export type HeroProps = {
    colorWaveBackground: string;
    colorWaveForeground: string;
}

export const Hero = ({ colorWaveBackground, colorWaveForeground }: HeroProps) => {
    return (
        <>
            <div className="h-screen sticky top-0 -z-10 scroll-snap flex flex-col justify-center sm:justify-start items-center sm:pt-[10vh]">
                <img src="tiredBlueWhale.png" alt="Tired Blue Whale Logo Large" className='max-h-[50vh] max-w-[80vw] pb-4 z-20' />
                <div className="flex flex-col px-8">
                    <span className="text-4xl sm:text-8xl text-center text-white">
                        Tired Blue Whale
                    </span>
                    <div className="h-1 bg-white" />
                    <span className="text-3xl sm:text-7xl text-center text-white">
                        Portfolio
                    </span>
                </div>
            </div>
            <div className="relative">
                <div className="absolute left-0 right-0 bottom-0 sm:bottom-5 -z-20">
                    <Wave waveColor={colorWaveBackground} index={0} />
                </div>
                <div className="absolute left-0 right-0 -bottom-5 z-0">
                    <Wave waveColor={colorWaveForeground} index={1} />
                </div>
            </div>
        </>
    )
}
